// Generated by CoffeeScript 1.4.0
var db, mongodbURL, mongodb_database, mongodb_host, mongodb_password, mongodb_port, mongodb_username, mongoose, schema;

mongoose = require('mongoose');

mongodb_username = process.env.mongodb_username || "admin";

mongodb_password = process.env.mongodb_password || "whoislikingyou";

mongodb_port = process.env.mongodb_port || 10072;

mongodb_host = process.env.mongodb_host || "alex.mongohq.com";

mongodb_database = process.env.mongodb_database || "whoislikingyou";

mongodbURL = "mongodb://" + mongodb_username + ":" + mongodb_password + "@" + mongodb_host + ":" + mongodb_port + "/" + mongodb_database;

db = mongoose.createConnection(mongodbURL);

schema = mongoose.Schema({
  category: String,
  name: String,
  access_token: String,
  _id: String
});

this.Page = db.model('Page', schema);

exports.upsert = function(page, callback) {
  var _this = this;
  this.Page.findOne({
    '_id': page.id
  }, function(err, pagedb) {
    if (err != null) {
      return callback(err);
    }
    if (!pagedb) {
      pagedb = new _this.Page({
        _id: page.id
      });
    }
    pagedb.category = page.category;
    pagedb.name = page.name;
    pagedb.access_token = page.access_token;
    return pagedb.save(function(err) {
      if (err != null) {
        return callback(err);
      }
    });
  });
  return callback(null);
};

exports.getAccess = function(pageId, callback) {
  var _this = this;
  return this.Page.findOne({
    '_id': pageId
  }, function(err, pagedb) {
    return callback(err, pagedb.access_token);
  });
};
