// Generated by CoffeeScript 1.4.0
var db, mongodbURL, mongodb_database, mongodb_host, mongodb_password, mongodb_port, mongodb_username, mongoose, schema;

mongoose = require('mongoose');

mongodb_username = process.env.mongodb_username || "admin";

mongodb_password = process.env.mongodb_password || "whoislikingyou";

mongodb_port = process.env.mongodb_port || 10072;

mongodb_host = process.env.mongodb_host || "alex.mongohq.com";

mongodb_database = process.env.mongodb_database || "whoislikingyou";

mongodbURL = "mongodb://" + mongodb_username + ":" + mongodb_password + "@" + mongodb_host + ":" + mongodb_port + "/" + mongodb_database;

db = mongoose.createConnection(mongodbURL);

schema = mongoose.Schema({
  username: 'string',
  email: 'string'
});

exports.upsert = function(user, data, callback) {
  return callback(null);
};

exports.insertByEmail = function(email, callback) {
  var User, userdb;
  User = db.model('User', schema);
  userdb = new User({
    username: '',
    email: email
  });
  return userdb.save(function(err) {
    if (err != null) {
      return callback(err);
    }
    return callback(null);
  });
};
