// Generated by CoffeeScript 1.4.0

module.exports = activatePage(function(data) {
  var user;
  user = require("../../data-layer/collections/user");
  return user.activatePage(req.user.email, req.body, function(err) {
    var response;
    response = req.user;
    response.activePage._id = req.body.id;
    response.activePage.name = req.body.name;
    return socket.emit("activatepage", err, response);
  });
});
