// Generated by CoffeeScript 1.4.0

module.exports = function(req, res, callback) {
  var user;
  user = require("../../data-layer/collections/user");
  return user.insertByEmail(req.body.email, res.locals.lingua.maillist, function(err, message) {
    return callback(err, message);
  });
};
