// Generated by CoffeeScript 1.4.0

module.exports = function(req, res, callback) {
  var user;
  user = require("../../data-layer/collections/user");
  return user.insertByEmail(req.body.email, function(err) {
    if (err != null) {
      return callback(err);
    }
    return callback(null);
  });
};
