// Generated by CoffeeScript 1.4.0
var restify;

restify = require('restify');

exports.get = function(url, callback) {
  var client,
    _this = this;
  client = restify.createJsonClient({
    url: 'https://graph.facebook.com'
  });
  return client.get(url, function(err, req, res, obj) {
    if (err != null) {
      return callback(err);
    }
    return callback(null, obj);
  });
};
