// Generated by CoffeeScript 1.4.0

exports.boot = function() {
  var UserClass, appId, appSecret, fS;
  UserClass = require("../../data-layer/collections/user");
  appId = process.env.appId || '111565172259433';
  appSecret = process.env.appSecret || '85f7e0a0cc804886180b887c1f04a3c1';
  this.passport.serializeUser(function(user, callback) {
    return callback(null, user.id);
  });
  this.passport.deserializeUser(function(id, callback) {
    return UserClass.User.findOne({
      _id: id
    }, function(err, user) {
      return callback(err, user);
    });
  });
  fS = this.facebookStrategy.Strategy;
  return this.passport.use(new fS({
    clientID: appId,
    clientSecret: appSecret,
    callbackURL: "/auth/facebook/callback"
  }, function(accessToken, refreshToken, profile, callback) {
    return UserClass.upsert(accessToken, profile, function(err, user) {
      return callback(err, user);
    });
  }));
};

exports.ensureAuthenticated = function(req, res, next) {
  if (req.isAuthenticated()) {
    return next();
  }
  return res.redirect('/home');
};
