// Generated by CoffeeScript 1.4.0

exports.logErrors = function(err, req, res, next) {
  console.error(err.stack);
  return next(err);
};

exports.clientErrorHandler = function(err, req, res, next) {
  if (req.xhr) {
    return res.send(500, {
      error: 'XHR error'
    });
  } else {
    return next(err);
  }
};

exports.errorHandler = function(err, req, res, next) {
  res.status(err.http_code || 500);
  return res.render("error", {
    layout: './user-interface/views/error/layout.toffee'
  });
};
