// Generated by CoffeeScript 1.4.0

exports.type = function(type, fn) {
  return function(req, res, next) {
    var ct;
    ct = req.headers['content-type'] || '';
    if (0 !== ct.indexOf(type)) {
      return next();
    }
    return fn(req, res, next);
  };
};
