// Generated by CoffeeScript 1.4.0

module.exports = function(app, myAuthentication) {
  app.get('/', function(req, res) {
    return res.render('public/index', {
      layout: null
    });
  });
  app.get('/:customer/:id', function(req, res, next) {
    return next();
  });
  app.post('/maillist', function(req, res) {
    var maillist;
    maillist = require("../maillist");
    return maillist(req, res, function(err) {
      if (err) {
        return res.send(500, {
          error: err
        });
      }
      return res.send(200);
    });
  });
  app.get('/app/login', myAuthentication.isAuth, function(req, res, next) {
    var login;
    login = require("../login");
    return login(req, res, function(err) {
      if (err != null) {
        return next(err);
      }
      return res.redirect("/app/dashboard");
    });
  });
  app.all('/app/:page', myAuthentication.isAuth, function(req, res, next) {
    var business_object, business_object_path;
    business_object_path = "../" + req.params.page.toString().toLowerCase();
    try {
      business_object = require(business_object_path);
    } catch (er) {
      return next();
    }
    return business_object(req, res, function(err, view, objectView) {
      if (err != null) {
        return next(err);
      }
      if (!(objectView != null)) {
        objectView = {};
      }
      objectView.user = req.session.auth.facebook.user;
      objectView.url = req.url;
      return res.render(view, objectView);
    });
  });
  app.get('*', myAuthentication.auth, function(req, res, next) {
    res.status(404);
    return res.render("public/404", {
      layout: "user-interface/views/public-layout.toffee",
      title: "Not found"
    });
  });
  return app.get('*', function(req, res) {
    return res.redirect("/");
  });
};
