// Generated by CoffeeScript 1.4.0

module.exports = function(app) {
  return app.get('/', function(req, res) {
    return res.render('public/index', {
      layout: "user-interface/views/index-layout.toffee",
      title: "Who Is Liking You?"
    });
  });
};
