// Generated by CoffeeScript 1.4.0

module.exports = function(app, myAuthentication, events) {
  app.get('/', function(req, res) {
    return res.redirect('/home');
  });
  app.all('/app/:page/:action?', myAuthentication.ensureAuthenticated, function(req, res, next) {
    var business_object, business_object_path;
    business_object_path = "../" + req.params.page.toString().toLowerCase();
    try {
      business_object = require(business_object_path);
    } catch (er) {
      return next();
    }
    console.log(req.xhr);
    if (req.xhr) {
      return business_object(req, res, events, function(err, message) {
        if (err != null) {
          return next(err);
        }
        return res.send(200, {
          message: message
        });
      });
    } else {
      return business_object(req, res, events, function(err, view, objectView) {
        if (err != null) {
          return next(err);
        }
        if (!(objectView != null)) {
          objectView = {};
        }
        objectView.user = req.user;
        objectView.url = req.url;
        return res.render(view, objectView);
      });
    }
  });
  app.get('/home', function(req, res) {
    return res.render('public/index', {
      layout: null
    });
  });
  app.get('/:customer/:id', function(req, res, next) {
    return next();
  });
  app.post('/maillist', function(req, res, next) {
    var maillist;
    maillist = require("../maillist");
    return maillist(req, res, function(err, message) {
      if (err != null) {
        return next(err);
      }
      return res.send(200, {
        message: message
      });
    });
  });
  app.get('/auth/facebook', myAuthentication.passport.authenticate('facebook', {
    scope: ['email', 'manage_pages', 'read_insights'],
    failureRedirect: '/home'
  }));
  app.get('/auth/facebook/callback', myAuthentication.passport.authenticate('facebook', {
    successRedirect: '/app/dashboard',
    failureRedirect: '/home'
  }));
  app.get('/logout', function(req, res) {
    req.logout();
    return res.redirect('/home');
  });
  app.get('*', myAuthentication.ensureAuthenticated, function(req, res, next) {
    res.status(404);
    return res.render("/404");
  });
  return app.get('*', function(req, res) {
    return res.redirect("/home");
  });
};
